CREATE TABLE IF NOT EXISTS protocols (
    id SERIAL PRIMARY KEY,
    slug VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    chain VARCHAR(100),
    category VARCHAR(100),
    tvl DECIMAL(20, 2) DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
