ethereum:
  chain_id: 1
  rpc: https://eth.llamarpc.com
  block_time: 12
arbitrum:
  chain_id: 42161
  rpc: https://arb1.arbitrum.io/rpc
  block_time: 0.25
polygon:
  chain_id: 137
  rpc: https://polygon-rpc.com
  block_time: 2
bsc:
  chain_id: 56
  rpc: https://bsc-dataseed.binance.org
  block_time: 3
optimism:
  chain_id: 10
  rpc: https://mainnet.optimism.io
  block_time: 2
avalanche:
  chain_id: 43114
  rpc: https://api.avax.network/ext/bc/C/rpc
  block_time: 2
